### ISSUE TITLE
csphere/php-fpm:5.4创建镜像失败

### ISSUE THREAD

**Issue by leo-livis** [nicescale/docker-training#1]
docker build -t csphere/php-fpm:5.4 .
在执行这条命令时,失败,上网查了一下是centos7.1的bug,在Dockerfile中所有的RUN之前添加一行后成功
RUN yum clean all && yum swap fakesystemd systemd -y
###### 
# 
# MAINTAINER        Carson,C.J.Zeong zcy@nicescale.com
# DOCKER-VERSION    1.6.2
# 
# Dockerizing php-fpm: Dockerfile for building php-fpm images
# 

FROM       csphere/centos:7.1
MAINTAINER Carson,C.J.Zeong zcy@nicescale.com
# Set environment variable

ENV     APP_DIR /app

RUN yum clean all && yum swap fakesystemd systemd -y
RUN     yum -y install nginx php-cli php-mysql php-pear php-ldap php-mbstring php-soap php-
        yum clean all

ADD nginx_nginx.conf /etc/nginx/nginx.conf
ADD     nginx_default.conf /etc/nginx/conf.d/default.conf

ADD     php_www.conf /etc/php-fpm.d/www.conf
RUN     sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php.ini

RUN     mkdir -p /app && echo "<?php phpinfo(); ?>" > ${APP_DIR}/info.php

EXPOSE  80 443

ADD     supervisor_nginx.conf /etc/supervisor.conf.d/nginx.conf
ADD     supervisor_php-fpm.conf /etc/supervisor.conf.d/php-fpm.conf

ONBUILD ADD . /app
ONBUILD RUN chown -R nginx:nginx /app

**Comment by tomtsang** [comment]
/sbin/ldconfig: Cannot lstat /lib64/libudev.so.1.4.0: No such file or directory


Rpmdb checksum is invalid: dCDPT(pkg checksums): elfutils-libs.x86_64 0:0.166-2.el7 - u
The command '/bin/sh -c yum clean all && yum swap fakesystemd systemd -y' returned a non-zero code: 1


我也报出了这个错误...怎么解?

**Comment by tomtsang** [comment]
--> Finished Dependency Resolution
Error: fakesystemd conflicts with systemd-219-30.el7_3.6.x86_64
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
fakesystemd-1-17.el7.centos.noarch has installed conflicts systemd: fakesystemd-1-17.el7.centos.noarch
The command '/bin/sh -c yum -y install nginx php-cli php-mysql php-pear php-ldap php-mbstring php-soap php-dom php-gd php-xmlrpc php-fpm php-mcrypt &&     yum clean all' returned a non-zero code: 1

如果没有加  `RUN yum clean all && yum swap fakesystemd systemd -y` , 则是报上面的错误..
怎么解决呢?
